from flask import Flask, render_template, request, Response
import joblib
import time
import os
import sys
from datetime import datetime

# Add the 'src' directory to path to import utils
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(os.path.join(BASE_DIR, 'src'))
from utils import clean_text

app = Flask(__name__)

# Paths to models
MODEL_PATH = os.path.join(BASE_DIR, 'models', 'phishing_model.pkl')
VECTOR_PATH = os.path.join(BASE_DIR, 'models', 'vectorizer.pkl')

# Load model and vectorizer
model = joblib.load(MODEL_PATH)
vectorizer = joblib.load(VECTOR_PATH)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/predict', methods=['POST'])
def predict():
    if request.method == 'POST':
        email_text = request.form['email_content']
        start_time = time.time()
        
        # Process
        cleaned_input = clean_text(email_text)
        vectorized_input = vectorizer.transform([cleaned_input])
        
        # Stats
        probabilities = model.predict_proba(vectorized_input)[0]
        risk_score = round(probabilities[1] * 100, 2)
        prediction_code = model.predict(vectorized_input)[0]
        
        latency = round((time.time() - start_time) * 1000, 2)
        result = "PHISHING" if prediction_code == 1 else "LEGITIMATE"
        word_count = len(email_text.split())

        return render_template('index.html', 
                               prediction=result, 
                               risk_score=risk_score,
                               latency=f"{latency} ms",
                               word_count=word_count,
                               original_text=email_text)

@app.route('/download', methods=['POST'])
def download():
    report_data = {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "result": request.form.get('prediction'),
        "risk": request.form.get('risk_score'),
        "content": request.form.get('original_text')
    }
    
    report_text = f"""
PHISHGUARD SECURITY ANALYSIS REPORT
====================================
Timestamp: {report_data['timestamp']}
Detection Result: {report_data['result']}
Risk Confidence: {report_data['risk']}%
====================================

ANALYZED CONTENT:
-----------------
{report_data['content']}

-----------------
Generated by PhishGuard AI Engine
Accuracy: 98.27%
    """
    return Response(
        report_text,
        mimetype="text/plain",
        headers={"Content-disposition": "attachment; filename=PhishGuard_Report.txt"}
    )

if __name__ == "__main__":
    app.run(debug=True, host='0.0.0.0', port=5000)